name: coffee_shop
description: A new Coffe Application with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0
  supercharged: ^2.0.0
  google_fonts: ^2.0.0
  flutter_spinkit: ^5.0.0
  get: ^4.1.4
  material_design_icons_flutter: ^4.0.5955
  intl: ^0.17.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/036-coffee-3.png
    - images/026-cookies.png
    - images/001-tea-4.png
    - images/013-lemonade.png
    - images/016-ice-cream.png
    - images/050-biscuit.png
    - images/024-cupcake.png
    - images/022-donut.png
    - images/hot-coffee-cinnamon.jpg
    - images/coffee-white.jpg
    - images/pile-cookies.jpg
    - images/account_circle_24px_rounded.png
    - images/shopping_cart_24px_rounded.png
    - images/store_mall_directory_24px_rounded.png
    - images/donuts.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
